from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from .commands import ffprobe_json
from .cost import CostTracker
from .models import create_intent
from .plan import create_edit_plan
from .policy import RunPolicy
from .qa import validate_launch_package
from .receipts import Receipts
from .render import render_long, render_shorts
from .review import build_review_packet
from .sources import discover_sources, lock_sources, write_manifest


@dataclass(frozen=True)
class RunResult:
    run_dir: Path
    status: str
    blockers: list[str]


def run_slug(folder: Path) -> str:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"{stamp}-{folder.name or 'footage'}"


def edit_folder(
    folder: Path,
    *,
    local_only: bool = False,
    cloud_budget_usd: float = 25.0,
    target_duration_s: float | None = None,
    host_intent_payload: dict[str, Any] | None = None,
) -> RunResult:
    sources = discover_sources(folder)
    run_dir = sources.folder / "eddy-runs" / run_slug(sources.folder)
    (run_dir / "final").mkdir(parents=True, exist_ok=True)
    (run_dir / "quarantine").mkdir(parents=True, exist_ok=True)
    receipts = Receipts(run_dir / "receipts.jsonl")
    policy = RunPolicy(local_only=local_only, cloud_budget_usd=cloud_budget_usd)
    cost = CostTracker(receipts, cap_usd=cloud_budget_usd)
    blockers: list[str] = []
    receipts.log("run_start", folder=str(sources.folder), local_only=local_only, cloud_budget_usd=cloud_budget_usd)
    before = lock_sources(sources, receipts, phase="before")
    write_manifest(run_dir, sources, before)
    try:
        intent = create_intent(
            sources,
            run_dir,
            receipts,
            policy,
            cost,
            target_duration_s=target_duration_s,
            host_intent_payload=host_intent_payload,
        )
        plan = create_edit_plan(sources, run_dir, intent, receipts)
        video = render_long(sources, run_dir, intent, receipts, policy, cost, plan=plan)
        shorts = render_shorts(sources, run_dir, intent, receipts, plan=plan)
        review_packet = build_review_packet(run_dir, video, shorts, receipts)
        if review_packet is None:
            blockers.append("review_packet_failed")
        write_launch_kit(run_dir, intent.as_dict(), video, shorts, plan=plan.as_dict(), review_packet=review_packet)
        write_scorecard(run_dir, cost.summary(), long_video=video, shorts=shorts, blockers=blockers, plan=plan.as_dict(), review_packet=review_packet)
        validate_launch_package(run_dir, video, shorts, receipts)
        receipts.log("gate", name="final_media_probe", status="pass", probe=ffprobe_json(video))
    except Exception as exc:
        blockers.append(str(exc))
        receipts.log("blocker", code="pipeline_failed", error=str(exc))
        write_scorecard(run_dir, cost.summary(), long_video=None, shorts=[], blockers=blockers, plan=None)
    finally:
        after = lock_sources(sources, receipts, phase="after")
        if before != after:
            blockers.append("source_hash_changed")
            receipts.log("blocker", code="source_hash_changed", before=before, after=after)
        receipts.log("run_finish", status="blocked" if blockers else "complete", blockers=blockers, **cost.summary())
    return RunResult(run_dir=run_dir, status="blocked" if blockers else "complete", blockers=blockers)


def write_launch_kit(run_dir: Path, intent: dict, video: Path, shorts: list[Path], *, plan: dict | None, review_packet: Path | None = None) -> None:
    kit = run_dir / "final" / "launch-kit"
    kit.mkdir(parents=True, exist_ok=True)
    chapters = [{"time": "00:00", "title": "Opening", "source": "fallback"}]
    if plan and plan.get("semantic_chapters"):
        chapters = plan["semantic_chapters"]
    data = {
        "title": intent["title"],
        "description": f"{intent['hook']}\n\nGenerated by Eddy V2 with proof-gated receipts.",
        "chapters": chapters,
        "long_video": str(video),
        "shorts": [str(p) for p in shorts],
        "edit_plan": plan,
        "review_packet": str(review_packet) if review_packet else None,
    }
    (kit / "launch-kit.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
    (kit / "README.md").write_text(f"# {data['title']}\n\n{data['description']}\n", encoding="utf-8")


def write_scorecard(
    run_dir: Path,
    cost_summary: dict,
    *,
    long_video: Path | None,
    shorts: list[Path],
    blockers: list[str],
    plan: dict | None,
    review_packet: Path | None = None,
) -> None:
    score = {
        "status": "blocked" if blockers else "complete",
        "long_video": str(long_video) if long_video else None,
        "shorts_count": len(shorts),
        "shorts": [str(p) for p in shorts],
        "blockers": blockers,
        "cost": cost_summary,
        "publishable_8_of_10": False,
        "notes": "Lennox taste score is required before claiming bakeoff victory.",
        "edit_plan": plan,
        "review_packet": str(review_packet) if review_packet else None,
    }
    (run_dir / "scorecard.json").write_text(json.dumps(score, indent=2), encoding="utf-8")
    (run_dir / "scorecard.md").write_text(
        "\n".join(
            [
                "# Eddy V2 Scorecard",
                "",
                f"- status: {score['status']}",
                f"- long_video: {score['long_video']}",
                f"- shorts_count: {score['shorts_count']}",
                f"- cost: ${cost_summary['spent_usd']:.4f} / ${cost_summary['cap_usd']:.2f}",
                f"- review_packet: {score['review_packet'] or 'none'}",
                f"- blockers: {', '.join(blockers) if blockers else 'none'}",
                "- publishable_8_of_10: false pending Lennox review",
                "",
            ]
        ),
        encoding="utf-8",
    )
